# Generated by Django 5.2.3 on 2025-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_update_free_user_quota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="questions_remaining",
            field=models.IntegerField(default=10),
        ),
    ]
