# This is the final, correct cloudbuild.yaml.
# It uses a standard Docker sidecar pattern with a named volume.

substitutions:
  _INSTANCE_CONNECTION_NAME: 'getdeepaiapp:us-central1:sec-db'
  _REGION: 'us-central1'
  _DB_PASSWORD_SECRET_ID: 'sec-insights-db-password'
  _DB_USER_SECRET_ID: 'sec-insights-db-user'
  _DB_NAME_SECRET_ID: 'sec-insights-db-name'
  _DJANGO_SECRET_KEY_SECRET_ID: 'sec-insights-django-secret-key'

logsBucket: 'gs://getdeepaiapp_cloudbuild'

steps:
# -----------------------------------------------------------------------------
# Step 1: Build the Django application image
# -----------------------------------------------------------------------------
- id: 'Build Django App Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID', 'backend/']

# -----------------------------------------------------------------------------
# Step 2: Push the Django application image
# -----------------------------------------------------------------------------
- id: 'Push App Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID']
  waitFor: ['Build Django App Image']

# -----------------------------------------------------------------------------
# Step 3: Run Django Database Migrations using a Docker Sidecar
# -----------------------------------------------------------------------------
- id: 'Run Django Migrations'
  name: 'gcr.io/cloud-builders/docker' # Use the standard Docker builder
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Create a named volume for the two containers to share the socket
    docker volume create cloudsql-socket

    # Start the official Cloud SQL Proxy image as a background container
    # It will place the socket file in the shared volume
    echo "Starting Cloud SQL Proxy container..."
    docker run \
      -d --name proxy \
      -v cloudsql-socket:/cloudsql \
      --network="cloudbuild" \
      gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0 \
      --unix-socket /cloudsql "${_INSTANCE_CONNECTION_NAME}"

    # Wait for the proxy container to start and create the socket
    sleep 10

    # Run migrations in the app container, connected to the same shared volume
    echo "Running migrations..."
    docker run --rm \
      -v cloudsql-socket:/cloudsql \
      --network="cloudbuild" \
      --env IS_CLOUD_ENV="True" \
      --env INSTANCE_CONNECTION_NAME="${_INSTANCE_CONNECTION_NAME}" \
      --env DB_NAME="$$DB_NAME" \
      --env DB_USER="$$DB_USER" \
      --env DB_PASSWORD="$$DB_PASSWORD" \
      --env SECRET_KEY="$$DJANGO_SECRET_KEY" \
      us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID \
      python manage.py migrate
  secretEnv: ['DB_PASSWORD', 'DB_USER', 'DB_NAME', 'DJANGO_SECRET_KEY']
  waitFor: ['Push App Image']

# -----------------------------------------------------------------------------
# Step 4: Collect Static Files
# -----------------------------------------------------------------------------
- id: 'Collect Static Files'
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--rm', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID', 'python', 'manage.py', 'collectstatic', '--noinput']
  env: ['IS_CLOUD_ENV=True', 'SECRET_KEY="$$DJANGO_SECRET_KEY"']
  secretEnv: ['DJANGO_SECRET_KEY']
  waitFor: ['Run Django Migrations']

# -----------------------------------------------------------------------------
# Step 5: Deploy the Django application to Cloud Run
# -----------------------------------------------------------------------------
- id: 'Deploy to Cloud Run'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'sec-insights-backend'
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=sec-insights-runner@getdeepaiapp.iam.gserviceaccount.com'
    - '--add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}'
    - '--set-env-vars=IS_CLOUD_ENV=True,INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
    - '--set-secrets=DB_NAME=${_DB_NAME_SECRET_ID}:latest,DB_USER=${_DB_USER_SECRET_ID}:latest,DB_PASSWORD=${_DB_PASSWORD_SECRET_ID}:latest,SECRET_KEY=${_DJANGO_SECRET_KEY_SECRET_ID}:latest'
  waitFor: ['Collect Static Files']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DB_PASSWORD_SECRET_ID}/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DB_USER_SECRET_ID}/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DB_NAME_SECRET_ID}/versions/latest
      env: 'DB_NAME'
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DJANGO_SECRET_KEY_SECRET_ID}/versions/latest
      env: 'DJANGO_SECRET_KEY'

