steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      - 'backend/' # Use the 'backend' directory as the build context

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID']

  # Step 3: Run database migrations securely
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      - '-s'
      - 'getdeepaiapp:us-central1:sec-db'
      # Inject secrets as environment variables
      - '-e'
      - 'DB_USER=${_DB_USER}'
      - '-e'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - '-e'
      - 'DB_NAME=${_DB_NAME}'
      # Set non-secret variables needed by settings.py
      - '-e'
      - 'IS_CLOUD_ENV=True' 
      - '-e'
      - 'SECRET_KEY=dummy-key-for-build' # Dummy key is fine for migrations
      - '--'
      # The command to run inside the container
      - 'python'
      - 'manage.py'
      - 'migrate'
    secretEnv: ['DB_PASSWORD', 'DB_USER', 'DB_NAME'] # Declare which env vars are secrets

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sec-insights-backend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=getdeepaiapp:us-central1:sec-db'
      - '--service-account=sec-insights-runner@getdeepaiapp.iam.gserviceaccount.com'
      - '--memory=2Gi'
      - '--set-secrets=DB_NAME=sec-insights-db-name:latest,DB_USER=sec-insights-db-user:latest,DB_PASSWORD=sec-insights-db-password:latest,SECRET_KEY=sec-insights-django-secret-key:latest'

# This block tells Cloud Build how to access the secrets
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sec-insights-db-password/versions/latest
    env: 'DB_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/sec-insights-db-user/versions/latest
    env: 'DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/sec-insights-db-name/versions/latest
    env: 'DB_NAME'

# This section automatically pushes the final image
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'