logsBucket: 'gs://getdeepaiapp_cloudbuild'

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      - 'backend/'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID']
    waitFor: ['Build']

  # Step 3: Run database migrations using substitution variables
  - name: 'gcr.io/google-appengine/exec-wrapper'
    id: Migrate
    args:
      - '-i'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      - '-s'
      - 'getdeepaiapp:us-central1:sec-db'
      - '-e'
      - 'IS_CLOUD_ENV=True'
      - '-e'
      - 'SECRET_KEY=dummy-key'
      - '-e'
      - 'INSTANCE_CONNECTION_NAME=getdeepaiapp:us-central1:sec-db'
      - '-e'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - '-e'
      - 'DB_USER=${_DB_USER}'
      - '-e'
      - 'DB_NAME=${_DB_NAME}'
      - '--'
      - 'python'
      - 'manage.py'
      - 'migrate'
    waitFor: ['Push']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
      - 'run'
      - 'deploy'
      - 'sec-insights-backend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=getdeepaiapp:us-central1:sec-db'
      - '--service-account=sec-insights-runner@getdeepaiapp.iam.gserviceaccount.com'
      - '--memory=2Gi'
      - '--set-env-vars=INSTANCE_CONNECTION_NAME=getdeepaiapp:us-central1:sec-db'
      - '--set-secrets=DB_NAME=sec-insights-db-name:latest,DB_USER=sec-insights-db-user:latest,DB_PASSWORD=sec-insights-db-password:latest,SECRET_KEY=sec-insights-django-secret-key:latest'
    waitFor: ['Migrate']
