# This cloudbuild.yaml is for DEBUGGING ONLY.
# It prints the environment variables to find the secret value issue.

substitutions:
  _INSTANCE_CONNECTION_NAME: 'getdeepaiapp:us-central1:sec-db'
  _REGION: 'us-central1'
  _DB_PASSWORD_SECRET_ID: 'sec-insights-db-password'
  _DB_USER_SECRET_ID: 'sec-insights-db-user'
  _DB_NAME_SECRET_ID: 'sec-insights-db-name'
  _DJANGO_SECRET_KEY_SECRET_ID: 'sec-insights-django-secret-key'

logsBucket: 'gs://getdeepaiapp_cloudbuild'

steps:
# Step 1 & 2 are the same: Build and Push the image
- id: 'Build Django App Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID', 'backend/']
- id: 'Push Django App Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID']
  waitFor: ['Build Django App Image']

# -----------------------------------------------------------------------------
# Step 3: DEBUG the Environment Variables
# -----------------------------------------------------------------------------
- id: 'Debug Environment Variables'
  name: 'gcr.io/google-appengine/exec-wrapper'
  args:
  - '-i'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'
  - '-s'
  - '${_INSTANCE_CONNECTION_NAME}'
  - '-e'
  - 'IS_CLOUD_ENV=True'
  - '-e'
  - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
  - '-e'
  - 'DB_NAME=$$DB_NAME'
  - '-e'
  - 'DB_USER=$$DB_USER'
  - '-e'
  - 'DB_PASSWORD=$$DB_PASSWORD'
  - '-e'
  - 'SECRET_KEY=$$DJANGO_SECRET_KEY'
  - '--'
  # The command is now 'printenv' to show all variables
  - 'printenv'
  secretEnv: ['DB_PASSWORD', 'DB_USER', 'DB_NAME', 'DJANGO_SECRET_KEY']
  waitFor: ['Push Django App Image']

# NOTE: The subsequent steps will be skipped or may fail, which is OK.
# We only care about the output from the "Debug Environment Variables" step.
# ...
