# This cloudbuild.yaml demonstrates building a Django app,
# running migrations, and deploying to Cloud Run with Cloud SQL.

substitutions:
  _INSTANCE_CONNECTION_NAME: 'getdeepaiapp:us-central1:sec-db'
  _REGION: 'us-central1'
  _DB_PASSWORD_SECRET_ID: 'sec-insights-db-password'
  _DB_USER_SECRET_ID: 'sec-insights-db-user'
  _DB_NAME_SECRET_ID: 'sec-insights-db-name'
  _DJANGO_SECRET_KEY_SECRET_ID: 'sec-insights-django-secret-key'

logsBucket: 'gs://getdeepaiapp_cloudbuild'

steps:
# -----------------------------------------------------------------------------
# Step 1: Build the Docker image for your Django application
# -----------------------------------------------------------------------------
- id: 'Build Django App Image'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'
    - 'backend/'  # Build context is the backend directory

# -----------------------------------------------------------------------------
# Step 2: Push the Docker image to Artifact Registry
# -----------------------------------------------------------------------------
- id: 'Push Django App Image'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'
  waitFor: ['Build Django App Image']

# -----------------------------------------------------------------------------
# Step 3: Run Django Migrations using Cloud SQL connection
# -----------------------------------------------------------------------------
- id: 'Run Django Migrations'
  name: 'gcr.io/google-appengine/exec-wrapper'
  args:
    - '-i'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'
    - '-s'
    - '${_INSTANCE_CONNECTION_NAME}'
    - '-e'
    - 'IS_CLOUD_ENV=True'
    - '-e'
    - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
    - '-e'
    - 'DB_NAME=$$DB_NAME'
    - '-e'
    - 'DB_USER=$$DB_USER'
    - '-e'
    - 'DB_PASSWORD=$$DB_PASSWORD'
    - '-e'
    - 'SECRET_KEY=$$DJANGO_SECRET_KEY'
    - '--'
    - 'python'
    - 'backend/manage.py'
    - 'migrate'
  secretEnv: ['DB_PASSWORD', 'DB_USER', 'DB_NAME', 'DJANGO_SECRET_KEY']
  waitFor: ['Push Django App Image']

# -----------------------------------------------------------------------------
# Step 4: Collect Static Files
# -----------------------------------------------------------------------------
- id: 'Collect Static Files'
  name: 'gcr.io/google-appengine/exec-wrapper'
  args:
    - '-i'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'
    - '-s'
    - '${_INSTANCE_CONNECTION_NAME}'
    - '-e'
    - 'IS_CLOUD_ENV=True'
    - '-e'
    - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
    - '-e'
    - 'DB_NAME=$$DB_NAME'
    - '-e'
    - 'DB_USER=$$DB_USER'
    - '-e'
    - 'DB_PASSWORD=$$DB_PASSWORD'
    - '-e'
    - 'SECRET_KEY=$$DJANGO_SECRET_KEY'
    - '--'
    - 'python'
    - 'backend/manage.py'
    - 'collectstatic'
    - '--noinput'
  secretEnv: ['DB_PASSWORD', 'DB_USER', 'DB_NAME', 'DJANGO_SECRET_KEY']
  waitFor: ['Run Django Migrations']

# -----------------------------------------------------------------------------
# Step 5: Deploy to Cloud Run
# -----------------------------------------------------------------------------
- id: 'Deploy to Cloud Run'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'sec-insights-backend'
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=sec-insights-runner@getdeepaiapp.iam.gserviceaccount.com'
    - '--memory=2Gi'
    - '--add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}'
    - '--set-env-vars=IS_CLOUD_ENV=True,INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
    - '--set-secrets=DB_NAME=${_DB_NAME_SECRET_ID}:latest,DB_USER=${_DB_USER_SECRET_ID}:latest,DB_PASSWORD=${_DB_PASSWORD_SECRET_ID}:latest,SECRET_KEY=${_DJANGO_SECRET_KEY_SECRET_ID}:latest'
  waitFor: ['Collect Static Files']

# -----------------------------------------------------------------------------
# Output Images
# -----------------------------------------------------------------------------
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID'

# -----------------------------------------------------------------------------
# Secret Manager Integration
# -----------------------------------------------------------------------------
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DB_PASSWORD_SECRET_ID}/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DB_USER_SECRET_ID}/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DB_NAME_SECRET_ID}/versions/latest
      env: 'DB_NAME'
    - versionName: projects/$PROJECT_NUMBER/secrets/${_DJANGO_SECRET_KEY_SECRET_ID}/versions/latest
      env: 'DJANGO_SECRET_KEY'
