logsBucket: gs://getdeepaiapp_cloudbuild'

steps:
  # 1. Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID',
        '.'
      ]

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      ]
    waitFor: ['Build']

  # 3. Run migrations securely
  - name: 'gcr.io/google-appengine/exec-wrapper'
    id: Migrate
    args:
      - '-i'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID'
      - '-s'
      - 'getdeepaiapp:us-central1:sec-db'
      - '-e'
      - 'IS_CLOUD_ENV=True'
      - '-e'
      - 'SECRET_KEY=dummy-key'
      - '-e'
      - 'INSTANCE_CONNECTION_NAME=getdeepaiapp:us-central1:sec-db'
      - '-e'
      - 'DB_NAME'
      - '-e'
      - 'DB_USER'
      - '-e'
      - 'DB_PASSWORD'
      - '--'
      - 'python'
      - 'manage.py'
      - 'migrate'
    secretEnv: ['DB_PASSWORD', 'DB_USER', 'DB_NAME']
    waitFor: ['Push']

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy sec-insights-backend \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$BUILD_ID \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --set-env-vars IS_CLOUD_ENV=True,SECRET_KEY=dummy-key \
          --set-secrets DB_PASSWORD=sec-insights-db-password:latest,DB_USER=sec-insights-db-user:latest,DB_NAME=sec-insights-db-name:latest \
          --set-env-vars INSTANCE_CONNECTION_NAME=getdeepaiapp:us-central1:sec-db
    waitFor: ['Migrate']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/sec-insights-db-password/versions/latest
      env: DB_PASSWORD
    - versionName: projects/$PROJECT_ID/secrets/sec-insights-db-user/versions/latest
      env: DB_USER
    - versionName: projects/$PROJECT_ID/secrets/sec-insights-db-name/versions/latest
      env: DB_NAME
