steps:
  # Step 1: Build the container image.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/sec-insights-backend:$BUILD_ID'
    - '-f'
    - 'backend/Dockerfile'
    - '--build-arg=DJANGO_BUILD_ENVIRONMENT=True'
    - '--build-arg=SECRET_KEY=build-time-dummy-key'
    - '.'

  # Step 2: Push the image to the registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sec-insights-backend:$BUILD_ID']

  # Step 3: Run database migrations against the PRODUCTION database.
- name: 'gcr.io/google-appengine/exec-wrapper'
  args:
    - '-i'
    - 'gcr.io/$PROJECT_ID/sec-insights-backend:$BUILD_ID'
    - '-s'
    - 'getdeepaiapp:us-central1:sec-db'
    - '-e'
    - 'DB_NAME=sec_db'
    - '-e'
    - 'DB_USER=sec_user'
    - '-e'
    - 'DB_PASSWORD=B#Y(mEd:*v/:0OJy'
    - '-e'
    - 'SECRET_KEY=$SECRET_KEY' # <-- THE CORRECTED LINE
    - '--'
    - 'python'
    - 'manage.py'
    - 'migrate'
  dir: 'backend'
  secretEnv: ['SECRET_KEY']

  # Step 4: Deploy the service to Cloud Run.
- name: 'gcr.io/google-cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'sec-insights-backend'
    - '--image=gcr.io/$PROJECT_ID/sec-insights-backend:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--set-secrets=SECRET_KEY=django-secret-key:latest'
    - '--set-env-vars=INSTANCE_CONNECTION_NAME=getdeepaiapp:us-central1:sec-db,DB_NAME=sec-db,DB_USER=sec_user,DB_PASSWORD=B#Y(mEd:*v/:0OJy'

images:
- 'gcr.io/$PROJECT_ID/sec-insights-backend:$BUILD_ID'

# Define the secret to be used in the build
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/django-secret-key/versions/latest
    env: 'SECRET_KEY'
