# -----------------------------------------------------------------------------
# Step 3: Run Django Database Migrations using the CUSTOM builder
# -----------------------------------------------------------------------------
- id: 'Run Django Migrations'
  name: 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/custom-builder:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Start proxy with the correct --unix-socket flag and wait
    echo "Starting Cloud SQL Proxy..."
    cloud-sql-proxy --unix-socket /cloudsql "${_INSTANCE_CONNECTION_NAME}" & # ✅ FIXED FLAG
    sleep 5 

    # Run migrations using docker
    echo "Running migrations..."
    docker run --rm \
      -v /cloudsql:/cloudsql \
      --network="cloudbuild" \
      --env IS_CLOUD_ENV="True" \
      --env INSTANCE_CONNECTION_NAME="${_INSTANCE_CONNECTION_NAME}" \
      --env DB_NAME="$$DB_NAME" \
      --env DB_USER="$$DB_USER" \
      --env DB_PASSWORD="$$DB_PASSWORD" \
      --env SECRET_KEY="$$DJANGO_SECRET_KEY" \
      us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-insights-backend:$BUILD_ID \
      python manage.py migrate
  secretEnv: ['DB_PASSWORD', 'DB_USER', 'DB_NAME', 'DJANGO_SECRET_KEY']
  waitFor: ['Push Images', 'Push App Image']
