steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$COMMIT_SHA',
      '.'
    ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$COMMIT_SHA'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sec-insights-backend
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --add-cloudsql-instances=projects/$PROJECT_ID/instances/sec-db
      - --set-secrets=DB_PASSWORD=sec-insights-db-password:latest,SECRET_KEY=sec-insights-django-secret-key:latest,EMAIL_HOST_USER=sec-insights-email-user:latest,EMAIL_HOST_PASSWORD=sec-insights-email-password:latest
      - --set-env-vars=DB_NAME=sec_db,DB_USER=sec_user,DB_HOST=/cloudsql/$PROJECT_ID:us-central1:sec-db,ENV=production

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sec-insights-repo/sec-backend:$COMMIT_SHA'
