# Generated by Django 5.2.3 on 2025-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sec_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("type", models.CharField(max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="sec_app_str_event_i_08a7a4_idx"
                    ),
                    models.Index(fields=["type"], name="sec_app_str_type_138f5b_idx"),
                ],
            },
        ),
    ]
