# Generated by Django 5.2.3 on 2025-10-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sec_app", "0002_stripeevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyMultiples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10, unique=True)),
                (
                    "numerators",
                    models.JSONField(
                        default=dict, help_text="Enterprise Value and Market Cap data"
                    ),
                ),
                (
                    "denominators",
                    models.JSONField(
                        default=dict, help_text="Financial metrics by period (1Y-15Y)"
                    ),
                ),
                (
                    "roic_metrics",
                    models.JSONField(default=dict, help_text="ROIC metrics by period"),
                ),
                (
                    "revenue_growth",
                    models.JSONField(
                        default=dict, help_text="Revenue growth CAGR by period"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Multiples",
                "verbose_name_plural": "Company Multiples",
                "db_table": "company_multiples",
                "ordering": ["ticker"],
            },
        ),
    ]
