# Generated by Django 5.2.8 on 2025-12-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sec_app", "0003_companymultiples"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "sectors",
                "ordering": ["name"],
            },
        ),
    ]
