# Generated by Django 5.2.8 on 2025-12-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0004_sector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBatch',
        ),
    ]
