# Generated by Django 5.2.3 on 2025-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0006_alter_company_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
