# Generated by Django 5.2.3 on 2025-07-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sec_app", "0008_chatsession_chathistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
