"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url


# Load environment variables from .env file
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))

# SEC API Settings with fallback values
SEC_API_KEY = os.getenv('SEC_API_KEY')
SEC_API_BASE_URL = os.getenv('SEC_API_BASE_URL', 'https://api.sec-api.io')

# SEC API Settings
SEC_USER_AGENT = os.getenv('SEC_USER_AGENT', 'Nanik Workforce paul@nanikworkforce.com')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-le1olj%(+vr!8xu+u&7q*%mhuctpi#l=qs$)hpmmf6z)^f$t8v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# SITE_URL = "https://sec-insights-app.onrender.com"


<<<<<<< HEAD
# Application definition
=======
# --- Environment Detection ---
IS_CLOUD_ENV = os.getenv('K_SERVICE', False) or os.getenv('GAE_APPLICATION', False)
IS_DOCKER_BUILD = os.getenv('DJANGO_BUILD_ENVIRONMENT', 'False') == 'True'


DEBUG = not IS_CLOUD_ENV and not IS_DOCKER_BUILD



if IS_DOCKER_BUILD:
    SECRET_KEY = os.environ.get('SECRET_KEY_BUILD_TIME')
else:
    SECRET_KEY = os.environ.get('SECRET_KEY')

if not SECRET_KEY and not (DEBUG or IS_DOCKER_BUILD): # Check for key if not in dev/build
    raise EnvironmentError("SECRET_KEY environment variable is not set. Required for production.")


# --- ALLOWED_HOSTS ---
ALLOWED_HOSTS = [
    'localhost',                     # For local dev
    '127.0.0.1',                     # Local IPv4
    '[::1]',                         # Local IPv6
    'sec-insights-backend-791634680391.us-central1.run.app', 
]

if IS_CLOUD_ENV:
    cloud_run_url = os.getenv('K_SERVICE_URL')
    if cloud_run_url:
        ALLOWED_HOSTS.append(cloud_run_url.split('//')[1].split('/')[0]) # Hostname
        ALLOWED_HOSTS.append(cloud_run_url) # Full URL
    ALLOWED_HOSTS.append('sec-insights-backend-791634680391.us-central1.run.app') # Explicit URL
elif IS_DOCKER_BUILD:
    ALLOWED_HOSTS.append('127.0.0.1')
    ALLOWED_HOSTS.append('localhost')
else:
    ALLOWED_HOSTS.append('127.0.0.1')
    ALLOWED_HOSTS.append('localhost')
    ALLOWED_HOSTS.append('[::1]') # IPv6
   

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME'),
#         'USER': os.environ.get('DB_USER'),
#         'PASSWORD': os.environ.get('DB_PASSWORD'),
#     }
# }

# if IS_CLOUD_ENV:
#     DATABASES['default']['HOST'] = f'/cloudsql/{os.environ.get("INSTANCE_CONNECTION_NAME")}'
#     print(f"INFO: Using Cloud Run DB config. Host: {DATABASES['default']['HOST']}")

# elif IS_DOCKER_BUILD:
#     DATABASES['default'] = dj_database_url.config(
#         default='sqlite:///tmp/build_db.sqlite3'
#     )
#     print("INFO: Using SQLite for Docker build environment (collectstatic).")

# else: # Local development
#     DATABASES['default']['HOST'] = os.environ.get('DB_HOST', '127.0.0.1')
#     DATABASES['default']['PORT'] = os.environ.get('DB_PORT', '5432')
#     print(f"INFO: Using Local DB config. Host: {DATABASES['default']['HOST']}:{DATABASES['default']['PORT']}")


DATABASES = {
    'default': {} # Start with an empty default
}

if IS_DOCKER_BUILD:
    print("INFO: Using SQLite for Docker build environment.")
    DATABASES['default'] = dj_database_url.config(
        default='sqlite:///tmp/build_db.sqlite3'
    )

elif IS_CLOUD_ENV:
    print("INFO: Using Cloud Run DB config.")
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
#        'HOST': f'/cloudsql/{os.environ.get("INSTANCE_CONNECTION_NAME")}',
#        'HOST': f'/cloudsql/{os.environ.get("INSTANCE_CONNECTION_NAME")}',
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    }

else:
    print("INFO: Using local SQLite database.")
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


print(f"DEBUG DB HOST: {DATABASES['default'].get('HOST')}")
print(f"DEBUG INSTANCE_CONNECTION_NAME: {os.environ.get('INSTANCE_CONNECTION_NAME')}")
print(f"DEBUG DB USER: {os.environ.get('DB_USER')}")
print(f"DEBUG DB PASSWORD: {os.environ.get('DB_PASSWORD')}")
print(f"DEBUG DB NAME: {os.environ.get('DB_NAME')}")

>>>>>>> 831378d44feea5df404107ec22ada80dd079f44b

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "channels",
    "rest_framework",
    "rest_framework_simplejwt",
    "account",
    "corsheaders",
    "sec_app",
    "django_filters",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # React frontend
    "https://sec-insights-app.vercel.app",

]

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'insightg_db',
#         'USER': 'insight_user',
#         'PASSWORD': 'InsightG123!',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = str(BASE_DIR / "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "account.User"

# Add these JWT settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
    ]
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Add logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'sec_app': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    'update-sec-filings': {
        'task': 'sec_app.tasks.update_sec_filings',
        'schedule': timedelta(days=1),  # Run daily
        'options': {'queue': 'sec_updates'}
    },
}

# Channels Configuration
ASGI_APPLICATION = "backend.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",  # Use Redis in production
    }
}

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') 
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'paul@nanikworkforce.com')

if DEBUG:
    SITE_URL = "http://localhost:3000"
else:
    SITE_URL = "https://sec-insights-app.vercel.app"

# Allow WebSockets
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
