# Generated by Django 5.1.7 on 2025-04-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xbrl_tag', models.CharField(max_length=100, unique=True)),
                ('standard_name', models.CharField(max_length=100)),
                ('priority', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('cik', models.CharField(max_length=10, unique=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'indexes': [models.Index(fields=['ticker'], name='sec_app_com_ticker_dc1358_idx')],
            },
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(help_text='Form type (e.g., 10-K, 10-Q)', max_length=10)),
                ('filing_date', models.DateField(help_text='Date the filing was submitted to SEC')),
                ('accession_number', models.CharField(blank=True, help_text='SEC accession number', max_length=20, null=True)),
                ('fiscal_year_end', models.DateField(blank=True, help_text='End date of the fiscal year', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='sec_app.company')),
            ],
            options={
                'db_table': 'sec_app_filing',
                'ordering': ['-filing_date'],
                'unique_together': {('company', 'filing_date', 'form')},
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=20)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], default='annual', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app.company')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app.company')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app.filing')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app.financialperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=10)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app.filingdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0.0)),
                ('xbrl_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(default='USD', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sec_app.company')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app.financialperiod')),
            ],
            options={
                'ordering': ['period', 'metric_name'],
                'unique_together': {('metric_name', 'period', 'company')},
            },
        ),
    ]
