# Generated by Django 5.0.2 on 2025-05-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cik',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
