# Generated by Django 5.0.2 on 2025-05-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0003_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
