# Generated by Django 5.1.7 on 2025-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0004_chatlog_context'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialmetric',
            index=models.Index(fields=['company', 'metric_name', 'period'], name='sec_app_fin_company_2545f4_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmetric',
            index=models.Index(fields=['metric_name'], name='sec_app_fin_metric__ff8e88_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmetric',
            index=models.Index(fields=['period'], name='sec_app_fin_period__b0e327_idx'),
        ),
    ]
