# Generated by Django 5.0.2 on 2025-06-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0005_financialmetric_sec_app_fin_company_2545f4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
