# Generated by Django 5.2.3 on 2025-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="questions_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro"), ("pro_plus", "Pro Plus")],
                default="free",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
